"""Setup script untuk Aleopantest V4.0.0"""
from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="aleopantest",
    version="4.0.2",
    author="Aleocrophic Team",
    author_email="deltaastra24@gmail.com",
    description="Advanced Penetration Testing Framework - 548+ Tools, Modern TUI, Cross-Platform",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/ZetaGo-Aurum/AleoPantest",
    packages=find_packages(),
    include_package_data=True,
    package_data={
        'aleopantest': ['web_assets/*', 'web_assets/**/*'],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Information Technology",
        "Topic :: Security",
        "Environment :: Console",
    ],
    python_requires=">=3.9",
    install_requires=[
        'click>=8.1.7',
        'rich>=13.9.0',
        'requests>=2.32.0',
        'beautifulsoup4>=4.12.3',
        'pydantic>=2.6.0',
        'pyyaml>=6.0.2',
        'textual>=0.89.0',
        'colorama>=0.4.6',
        'python-dotenv>=1.0.1',
        'dnspython>=2.7.0',
        'tqdm>=4.67.0',
        'psutil>=6.1.0',
        'prompt_toolkit>=3.0.48',
        'fastapi>=0.115.0',
        'uvicorn>=0.34.0',
        'python-multipart>=0.0.18',
        'jinja2>=3.1.5',
        'httpx>=0.28.0',
    ],
    extras_require={
        'web': [
            'fastapi>=0.115.0',
            'uvicorn>=0.34.0',
            'python-multipart>=0.0.18',
            'jinja2>=3.1.5',
            'httpx>=0.28.0',
        ],
        'full': [
            'fastapi>=0.115.0',
            'uvicorn>=0.34.0',
            'python-multipart>=0.0.18',
            'jinja2>=3.1.5',
            'httpx>=0.28.0',
            'scapy>=2.6.0',
            'python-nmap>=0.7.1',
            'paramiko>=3.5.0',
            'pycryptodome>=3.21.0',
            'sqlalchemy>=2.0.36',
            'shodan>=1.31.0',
            'cryptography>=44.0.0',
            'impacket>=0.12.0',
            'ldap3>=2.9.1',
            'boto3>=1.35.0',
            'docker>=7.1.0',
        ],
        'cloud': [
            'boto3>=1.35.0',
            'docker>=7.1.0',
        ],
        'wireless': [
            'scapy>=2.6.0',
        ],
    },
    entry_points={
        'console_scripts': [
            'aleopantest=aleopantest.cli:cli',
            'alpnts=aleopantest.cli:cli',
        ],
    },
)
